export const DEFAULT_OFFSET_TOP = 12
export const DEFAULT_OFFSET_BOTTOM = 4
export const DEFAULT_POSITION_THRESHOLD = 2
export const DEFAULT_OVERFLOW_PADDING = 16
export const DEFAULT_HOVER_GAP_TOLERANCE = 100
export const DEFAULT_HOVER_OPEN_DELAY = 0
export const DEFAULT_HOVER_CLOSE_DELAY = 300

export const RECALC_TIMEOUT_MS = 10
export const DEBOUNCE_DEFAULT_DELAY_MS = 100
export const DEBOUNCE_RESIZE_DELAY_MS = 50
export const DEBOUNCE_MUTATION_DELAY_MS = 100
export const DEBOUNCE_WINDOW_RESIZE_DELAY_MS = 150
export const DEBOUNCE_CONTENT_CHANGE_DELAY_MS = 200
export const TIME_SINCE_LAST_RECALC_THRESHOLD_MS = 200
export const AUTO_REPOSITION_DELAY_MS = 16

export const MODAL_Z_INDEX = 50
